---
title: "Gut Model Development"
author: "Emmi Mueller and Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
output: pdf_document
geometry: margin = 2.54cm
---
Overview: Pilot experiment with gut model

##Set up environment
```{r, results = 'hide', warning=FALSE, message=FALSE}
rm(list=ls())

package.list <- c('plyr', 'grid', 'png', 'ggplot2', 'tidyverse', 'here', 'ggpmisc', 'Hmisc', 'ggsignif', 'ggpubr') 
for (package in package.list) {
  if (!require(package, character.only=T, quietly=T)) { 
    install.packages(package)
    library(package, character.only=T)
  } }

here()
```
#Set up figure themes
```{r figure_setup}
my.cols <- RColorBrewer::brewer.pal(n = 4, name = "Greys")[3:4]

# Set theme for figures in the paper
theme_set(theme_classic() + 
  theme(axis.title = element_text(size = 15),
        axis.title.x = element_text(margin = margin(t = 15, b = 15)),
        axis.title.y = element_text(margin = margin(l = 15, r = 15)),
        axis.text = element_text(size = 15),
        axis.text.x = element_text(margin = margin(t = 5)),
        axis.text.y = element_text(margin = margin(r = 5)),
        axis.line.x = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.x = element_line(size = 1),
        axis.ticks.y = element_line(size = 1),
        axis.ticks.length = unit(.1, "in"),
        panel.border = element_rect(color = "black", fill = NA, size = 1.5),
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 15),
        strip.text = element_text(size = 20),
        strip.background = element_blank()
        ))
```
## Read in file in .csv format with columns day, abundance, and complexity level
## Set up functions: sem, 
```{r}
#abundance <- read.table(here("data", "GM_pilot","20190219_0904_PilotAbundance.csv"), header = TRUE, sep = ",")
abundance <- read.table(here("data", "GM_pilot", "20201029_1354_HLTPilotAbundance.csv"), header = TRUE, sep = ",")
abundance$Abundance <- abundance$P1.Abs..Count - abundance$PBS

#oxygen <- read.table(here("data", "GM_pilot", "Oxygen_Pilot_20190926.csv"), header = TRUE, sep = ",")
oxygen <- read.table(here("data", "GM_pilot", "Oxygen_Pilot_20201029.csv"), header = TRUE, sep = ",")

sem <- function(x, ...){sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))}

ttest <- function(reg, coefnum, val){
  co <- coef(summary(reg))
  tstat <- (co[coefnum,1]-val)/co[coefnum,2]
  pstat <- 2 * pt(abs(tstat), reg$df.residual, lower.tail = FALSE)
  return(list = c(t = tstat, df = reg$df.residual, p =  pstat))
}
```

## Clean and transform data
```{r}
#Abundance data
abundance$Log <- log10(abundance$Abundance)
abundance$Hrs <- (abundance$Day *24)

#Oxygen data
oxygen.means <- aggregate(Concentration ~Oxygen, data = oxygen, FUN = mean) 
oxygen.n <- aggregate(Concentration ~Oxygen, data = oxygen, FUN = length) 
oxygen.sem <- aggregate(Concentration ~Oxygen, data = oxygen, FUN = sem) 
oxygen.95.LL <- aggregate(Concentration ~Oxygen, data = oxygen,
          FUN = function(x) t.test(x)$conf.int[1])
oxygen.95.UL <- aggregate(Concentration ~Oxygen, data = oxygen,
          FUN = function(x) t.test(x)$conf.int[2])

oxygen.table <- data.frame(oxygen.means, oxygen.sem[ ,2], oxygen.n[ ,2], 
                           oxygen.95.LL[,2], oxygen.95.UL[,2])
colnames(oxygen.table) <- c("oxygen", "mean", "sem", "n", "95LL", "95UL")
```

## Plot abundance pilot data
```{r}
summary(lm(abundance$Log~abundance$Hrs))
ggplot(abundance,aes(x= Day, y= Log, group = Gut, color = Gut))+
  geom_line()+
  geom_point(cex = 1.5)+
  xlab("Days") +
  ylab("log(Abundance (cells/mL))")+
  ylim(c(0, 12))

ggsave(here("output", "HLTPilot.abundance.pdf"), dpi = 400, width = 6, height = 5)
ggsave(here("output", "HLTPilot.abundance.png"), dpi = 400, width = 6, height = 5)
```
#Abundance GM_Pilot
```{r}
summary(lm(abundance$Log~abundance$Hrs))
ggplot(abundance,aes(x= Hrs, y= Log, group = Gut, color = Gut))+
  geom_line()+
  geom_point(cex = 1.5)+
  xlab("Time (hrs)") +
  ylab("log(Abundance (cells/mL))")+
  ylim(c(0, 12))

ggsave(here("output", "HLTPilot.abundance.pdf"), dpi = 400, width = 6, height = 5)
ggsave(here("output", "HLTPilot.abundance.png"), dpi = 400, width = 6, height = 5)
```

##Abundance summary statistics
```{r}

abundance_summary <- summary(abundance$Log)
abundance_sem <- sem(abundance$Log)
abundance_cv <- sd(abundance$Log)/mean(abundance$Log)

```

## Plot oxygen pilot data
```{r}
oind<-order(as.numeric(by(oxygen$Concentration, oxygen$Oxygen,median,na.rm=T)), decreasing = T)
oxygen$Oxygen<-ordered(oxygen$Oxygen,levels=levels(oxygen$Oxygen)[oind])
t.test(oxygen[which(oxygen$Oxygen == "Gut"),"Concentration"], oxygen[which(oxygen$Oxygen == "Media"),"Concentration"])

ggplot(oxygen, aes(x = Oxygen, y = Concentration))+
  geom_jitter(width = 0.2, height = 0.1, size=2,alpha=0.6, color = "grey")+
  ylab("Dissolved oxygen (mg/L)")+
  xlab("")+
  scale_x_discrete(labels=c("Media" = "Feed", "Gut" = "Reactor"))+
  scale_y_continuous(limits = c(-0.1, 8))+
  stat_summary(fun.data="mean_se", fun.args = list(mult=1), 
                geom="errorbar", width=0.3, color = "black")+
  stat_summary(fun.data="mean_se", fun.args = list(mult=2),
                geom = "point", color = "black", pch = 1, size = 4)+
  geom_signif(comparisons=list(c("Media", "Gut")), annotations="*",
              y_position= 8, tip_length = 0, vjust=0.4)+
  annotate("text", x = 2.3, y = 8, label = "p = 0.025", cex = 2)

ggsave(here("output", "HLTPilot_oxygen.pdf"))
ggsave(here("output", "HLTPilot_oxygen.png"), height = 4, width =3)
```
```


